{{- $apiKey := .Values.secrets.apiKey | default (randAlphaNum 32) | b64enc  }}
{{- $mongo :=  .Values.secrets.mongoUrl | b64enc -}}
{{- $apiUrl := .Values.secrets.apiUrl | b64enc -}}
{{- $oneSignalAppId := .Values.secrets.apiUrl | b64enc -}}
{{- $notificationLargeIcon := .Values.secrets.apiUrl | b64enc -}}
{{- $oneSignalToken := .Values.secrets.apiUrl | b64enc -}}
{{- $oneSignalUrl := .Values.secrets.apiUrl | b64enc -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "api-hra-secrets") }}
{{- if $secret }}
{{- $apiKey = index $secret.data "api-key" }}
{{- $mongo = index $secret.data "mongo"}}
{{- $apiUrl = index $secret.data "api-url" }}
{{- $oneSignalAppId = index $secret.data "one-signal-app-id" }}
{{- $notificationLargeIcon = index $secret.data "notification-large-icon" }}
{{- $oneSignalToken = index $secret.data "one-signal-token" }}
{{- $oneSignalUrl = index $secret.data "one-signal-url" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "api-interna-notificaciones.fullname" .) | printf "%s-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-interna-notificaciones.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $apiKey }}
  mongo: {{ $mongo }}
  api-url: {{ $apiUrl }}
  one-signal-app-id: {{ $oneSignalAppId }}
  notification-large-icon: {{ $notificationLargeIcon }}
  one-signal-token: {{ $oneSignalToken }}
  one-signal-url: {{ $oneSignalUrl }}
